services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=db:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD_FILE=/run/secrets/gitea_db_password_v1
    secrets:
      - gitea_db_password_v1
    restart: always
    volumes:
      - gitea_data:/data
    ports:
      - "3000:3000"
      - "22:22"
    networks:
      - gitea_network
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        compress: "true"

  db:
    image: mysql:latest
    container_name: gitea_mysql
    restart: always
    environment:
      - MYSQL_DATABASE=gitea
      - MYSQL_USER=gitea
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password_v1
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_user_password_v1
    secrets:
      - mysql_root_password_v1
      - mysql_user_password_v1
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - gitea_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--password=$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        compress: "true"

volumes:
  gitea_data:
  mysql_data:

networks:
  gitea_network:
    driver: bridge

secrets:
  mysql_root_password_v1:
    file: ./secrets/mysql_root_password_v1
  mysql_user_password_v1:
    file: ./secrets/mysql_user_password_v1
  gitea_db_password_v1:
    file: ./secrets/gitea_db_password_v1
